import React,{useState,useEffect} from 'react';import {useNavigate} from 'react-router-dom';import {motion} from 'framer-motion';import {DollarSign,Building2,FileText,TrendingUp,Radio,Gift} from 'lucide-react';import {useConfig} from '../context/ConfigContext';import {useAuth} from '../context/AuthContext';import {useLang} from '../context/LangContext';import {LoadingPage} from '../components/Skeleton';import HomeSlider from '../components/HomeSlider';import axios from 'axios';
const API=process.env.REACT_APP_API_URL||'http://localhost:5000/api';
const c={hidden:{opacity:0},show:{opacity:1,transition:{staggerChildren:0.08}}};const i={hidden:{opacity:0,y:20},show:{opacity:1,y:0}};
export default function Home(){
  const [load,setLoad]=useState(true);const [users,setUsers]=useState([]);const {cfg}=useConfig();const {user}=useAuth();const {t}=useLang();const nav=useNavigate();
  useEffect(()=>{const tm=setTimeout(()=>setLoad(false),1200);axios.get(`${API}/auth/recent`).then(r=>setUsers(r.data)).catch(()=>{});return()=>clearTimeout(tm);},[]);
  if(load)return<LoadingPage/>;
  const acts=[{icon:DollarSign,label:t.deposit,desc:'أضف رصيد',path:'/deposit',bg:'bg-teal-50',col:'text-teal-600'},{icon:Building2,label:t.about,desc:'تعرف علينا',path:'/about',bg:'bg-blue-50',col:'text-blue-600'},{icon:FileText,label:t.withdraw,desc:'اسحب أرباحك',path:'/withdraw',bg:'bg-purple-50',col:'text-purple-600'},{icon:TrendingUp,label:t.records,desc:'المعاملات',path:'/mine',bg:'bg-orange-50',col:'text-orange-600'}];
  const activities=[{title:'تتبع القناة الرسمية',reward:'+0.10 USDT',icon:Gift,col:'text-pink-500',bg:'bg-pink-50'},{title:'مشاركة إعلانات تيليجرام',reward:'+2.00 USDT',icon:Gift,col:'text-blue-500',bg:'bg-blue-50'},{title:'مشاركة إعلانات الواتساب',reward:'+2.00 USDT',icon:Gift,col:'text-green-500',bg:'bg-green-50'},{title:'مشاركة إعلانات الفيسبوك',reward:'+5.00 USDT',icon:Gift,col:'text-indigo-500',bg:'bg-indigo-50'},{title:'تكبير مشاركة الإعلانات',reward:'+50.00 USDT',icon:Gift,col:'text-purple-500',bg:'bg-purple-50'}];
  return(
  <motion.div variants={c}initial="hidden"animate="show"className="pb-24 max-w-lg mx-auto">
  <motion.div variants={i}className="relative mx-2 rounded-b-3xl overflow-hidden text-white p-6"style={{background:`linear-gradient(135deg,${cfg.primaryColor},${cfg.secondaryColor})`}}>
  <div className="relative z-10"><motion.h1 initial={{x:20,opacity:0}}animate={{x:0,opacity:1}}className="text-2xl font-bold mb-1">برنامج</motion.h1><p className="text-white/80 text-sm">تعدين ZEC الاحترافي بأعلى عوائد</p></div>
  <motion.div animate={{rotate:[0,5,-5,0]}}transition={{repeat:Infinity,duration:6}}className="absolute top-2 left-4 opacity-10"><TrendingUp className="w-32 h-32"/></motion.div>
  </motion.div>
  <motion.div variants={i}className="grid grid-cols-2 gap-3 p-4">{acts.map((a,idx)=>(<motion.div key={idx}whileHover={{scale:1.03,y:-3}}whileTap={{scale:0.97}}onClick={()=>nav(a.path)}className={`${a.bg} rounded-2xl p-4 cursor-pointer shadow-sm hover:shadow-md transition border border-gray-100`}><div className={`w-11 h-11 rounded-xl ${a.bg} flex items-center justify-center mb-2`}><a.icon className={`w-5 h-5 ${a.col}`}/></div><h3 className="font-bold text-gray-800 text-sm">{a.label}</h3><p className="text-[11px] text-gray-500 mt-0.5">{a.desc}</p></motion.div>))}</motion.div>
  <motion.div variants={i}className="mx-4 bg-white rounded-xl p-3 shadow-sm flex items-center gap-2 text-xs text-gray-600 border border-gray-100"><TrendingUp className="w-4 h-4 text-green-500 shrink-0"/><span className="truncate">{cfg.tickerText}</span></motion.div>
  <HomeSlider/>
  <motion.div variants={i}className="p-4"><h2 className="font-bold text-lg mb-3 text-gray-800 flex items-center gap-2"><span className="w-1 h-5 rounded-full bg-primary"></span>{t.activities}</h2><div className="space-y-3">{activities.map((act,idx)=>(<motion.div key={idx}variants={i}whileHover={{x:-4}}className="bg-white rounded-xl p-4 shadow-sm flex items-center justify-between border border-gray-50"><div className="flex items-center gap-3"><div className={`w-10 h-10 rounded-lg ${act.bg} flex items-center justify-center`}><act.icon className={`w-5 h-5 ${act.col}`}/></div><div><h4 className="font-semibold text-sm">{act.title}</h4><p className="text-[11px] text-gray-400">شارك واربح</p></div></div><div className="text-right"><span className="text-green-600 font-bold text-sm">{act.reward}</span><motion.button whileTap={{scale:0.9}}className="block mt-1 text-[11px] text-white px-3 py-1 rounded-full"style={{backgroundColor:cfg.primaryColor}}>يتبع</motion.button></div></motion.div>))}</div></motion.div>
  <motion.div variants={i}className="p-4"><h2 className="font-bold text-lg mb-3 text-gray-800 flex items-center gap-2"><span className="w-1 h-5 rounded-full bg-primary"></span>{t.projectHall}</h2><div className="space-y-4">{[{name:'زيك مينر 0',daily:1.70,price:6.00,days:30},{name:'زيك مينر 1',daily:2.60,price:12.00,days:90},{name:'زيك مينر 2',daily:17.29,price:79.00,days:90}].map((pl,idx)=>(<motion.div key={idx}variants={i}whileHover={{y:-2}}className="bg-white rounded-2xl p-4 shadow-sm border border-gray-100"><div className="flex items-center gap-4"><motion.img whileHover={{rotate:10}}src={cfg.logo}className="w-14 h-14 rounded-xl object-cover shadow-sm"alt="miner"/><div className="flex-1"><h3 className="font-bold text-sm">{pl.name}</h3><div className="text-xs text-gray-500 mt-1 space-y-0.5"><p>الربح اليومي: <span className="font-bold"style={{color:cfg.primaryColor}}>{pl.daily} USDT</span></p><p>دورة: {pl.days} يوم | غير محدود</p></div></div></div><motion.button whileTap={{scale:0.97}}className="w-full mt-3 bg-gray-900 text-white py-2.5 rounded-xl text-sm font-bold hover:bg-black transition">{t.buyNow} {pl.price} USDT</motion.button></motion.div>))}</div></motion.div>
  <motion.div variants={i}className="p-4"><h2 className="font-bold text-lg mb-3 text-gray-800 flex items-center gap-2"><span className="w-1 h-5 rounded-full bg-primary"></span>{t.members}</h2><div className="space-y-2">{users.map((m,idx)=>(<motion.div key={idx}initial={{opacity:0,x:20}}animate={{opacity:1,x:0}}transition={{delay:idx*0.1}}className="bg-white rounded-xl p-3 flex justify-between items-center shadow-sm border border-gray-50"><span className="text-sm text-gray-600">{m.email}</span><span className="text-green-600 font-bold text-sm">{m.amount}</span></motion.div>))}</div></motion.div>
  </motion.div>);
}
