import React,{createContext,useContext,useState} from 'react';
const ar={login:'تسجيل الدخول',register:'إنشاء حساب',email:'البريد الإلكتروني',password:'كلمة المرور',confirmPassword:'أعد إدخال كلمة المرور',phone:'رقم الهاتف',inviteCode:'رمز الدعوة',submit:'اشتراك',haveAccount:'تسجيل الدخول',noAccount:'ليس لديك حساب؟',createNow:'سجل الآن',home:'بيت',projects:'المشاريع',team:'فريق',me:'أنا',deposit:'إيداع',withdraw:'ينسحب',about:'معلومات عنا',records:'سجلات',balance:'الرصيد الإجمالي',depositAmount:'مبلغ الإيداع',settings:'الإعدادات',admin:'لوحة التحكم',logout:'تسجيل الخروج',changePassword:'تغيير كلمة المرور',activities:'الفعاليات',projectHall:'قاعة المشروع',members:'أعضاء',buyNow:'اشتري الآن',dailyProfit:'الربح اليومي',cycle:'دورة',unlimited:'غير محدود',teamSize:'حجم الفريق',teamDeposits:'ودائع الفريق',teamEarnings:'إسهامات الفريق',newMembers:'الأعضاء الجدد',firstDeposits:'الودائع الأولى',firstWithdrawals:'عمليات السحب الأولى',level:'مستوى',registeredActive:'مسجل/نشط',commissionRate:'نسبة المسؤلة',totalIncome:'إجمالي الدخل',details:'تفاصيل',copy:'نسخ',shareLink:'شارك رابط الإحالة الخاص بك',welcomeBack:'Welcome back',enterAmount:'أدخل الكمية',withdrawAddress:'عنوان السحب',youWillReceive:'ستتلقى',confirm:'يتأكد',selectCurrency:'اختر العملة',walletAddress:'عنوان المحفظة',depositDone:'تم الإيداع',copyAddress:'نسخ العنوان',aboutUs:'معلومات عنا',contact:'بيانات التواصل',channel:'قناة تيليجرام الرسمية',customize:'التخصيص العام',branding:'العلامة التجارية',primaryColor:'اللون الأساسي',secondaryColor:'اللون الثانوي',appName:'اسم التطبيق',logoUrl:'رابط اللوجو',ticker:'نص الشريط المتحرك',save:'حفظ التغييرات',saved:'تم الحفظ!',slides:'صور السلايدر',addSlide:'إضافة صورة',plans:'الباقات',addPlan:'إضافة باقة',name:'الاسم',price:'السعر',days:'الأيام',imageUrl:'رابط الصورة',active:'نشط',limited:'محدود',delete:'حذف',add:'إضافة',cancel:'إلغاء'};
const en={login:'Login',register:'Register',email:'Email',password:'Password',confirmPassword:'Confirm Password',phone:'Phone Number',inviteCode:'Invite Code',submit:'Sign Up',haveAccount:'Login',noAccount:"Don't have an account?",createNow:'Register now',home:'Home',projects:'Projects',team:'Team',me:'Me',deposit:'Deposit',withdraw:'Withdraw',about:'About Us',records:'Records',balance:'Total Balance',depositAmount:'Deposit Amount',settings:'Settings',admin:'Admin Dashboard',logout:'Logout',changePassword:'Change Password',activities:'Activities',projectHall:'Project Hall',members:'Members',buyNow:'Buy Now',dailyProfit:'Daily Profit',cycle:'Cycle',unlimited:'Unlimited',teamSize:'Team Size',teamDeposits:'Team Deposits',teamEarnings:'Team Earnings',newMembers:'New Members',firstDeposits:'First Deposits',firstWithdrawals:'First Withdrawals',level:'Level',registeredActive:'Registered/Active',commissionRate:'Commission Rate',totalIncome:'Total Income',details:'Details',copy:'Copy',shareLink:'Share your referral link',welcomeBack:'Welcome back',enterAmount:'Enter Amount',withdrawAddress:'Withdraw Address',youWillReceive:'You will receive',confirm:'Confirm',selectCurrency:'Select Currency',walletAddress:'Wallet Address',depositDone:'Deposit Done',copyAddress:'Copy Address',aboutUs:'About Us',contact:'Contact Info',channel:'Official Telegram Channel',customize:'Customization',branding:'Branding',primaryColor:'Primary Color',secondaryColor:'Secondary Color',appName:'App Name',logoUrl:'Logo URL',ticker:'Ticker Text',save:'Save Changes',saved:'Saved!',slides:'Slider Images',addSlide:'Add Slide',plans:'Plans',addPlan:'Add Plan',name:'Name',price:'Price',days:'Days',imageUrl:'Image URL',active:'Active',limited:'Limited',delete:'Delete',add:'Add',cancel:'Cancel'};
const Ctx=createContext();
export function LangProvider({children}){
  const [lang,setLang]=useState(localStorage.getItem('zecLang')||'ar');
  const t=lang==='ar'?ar:en;
  const toggle=()=>{const n=lang==='ar'?'en':'ar';setLang(n);localStorage.setItem('zecLang',n);};
  return <Ctx.Provider value={{lang,t,toggle}}>{children}</Ctx.Provider>;
}
export const useLang=()=>useContext(Ctx);
